site_name: 服务器使用指南
theme: readthedocs
site_name: My Docs

nav:
  - 首页: index.md
  - 快速指南:
    - 快速开始: guides/quickstart.md
    - 存储说明: guides/storage.md
  - 环境配置:
    - 基础环境:
      - CUDA安装: env/cuda.md
      - Conda管理: env/conda.md
  - 开发工具链:
    - IDE配置:
      - PyCharm配置: tools/pycharm.md

plugins:
  - search

markdown_extensions:
- codehilite

# extra_css:
#   - css/custom.css