site_name: 服务器使用指南
theme: readthedocs
site_name: My Docs

nav:
  - 首页: index.md
  - 快速指南:
    - 快速开始: guides/quickstart.md
    - 故障排查: guides/troubleshooting.md
  - 实践案例: 
    - 并行训练: 
      - LLaMA多卡训练: practices/llama-multigpu.md
      - SD分布式: practices/sd-distributed.md
    - 推理优化:
      - CLIP多卡推理: practices/clip-multigpu.md
      - 视频理解流水线: practices/video-pipeline.md
    - 基准测试:
      - 吞吐量压测: practices/throughput-test.md
      - NCCL带宽测试: practices/nccl-bandwidth.md
    - 专项测试:
      - 实时推理测试: practices/realtime-inference.md
      - 弹性训练测试: practices/elastic-training.md
      - 容错训练恢复: practices/fault-tolerant.md
  - 环境配置:
    - 系统配置:
      - OS安装: env/os-install.md
      - GPU驱动: env/gpu-driver.md
      - 存储配置: env/storage.md
    - 基础环境:
      - CUDA安装: env/cuda.md
      - Conda管理: env/conda.md
      - Docker配置: env/docker.md
    - 深度学习环境:
      - 多租户隔离: env/multi-tenant.md
      - 预训练权重: env/pretrained-weights.md
  - 开发工具链:
    - IDE配置:
      - PyCharm配置: tools/pycharm.md
      - VSCode配置: tools/vscode.md
      - Cursor配置: tools/cursor.md
    - 远程协作:
      - SSH远程连接: tools/ssh-remote.md
      - VNC配置指南: tools/vnc-conf.md
      - 向日葵远程控制: tools/sunlogin.md
    - 输入法配置: tools/input-method.md
  - 系统运维:
    - 任务管理:
      - 监控系统: devops/monitoring.md
      - 调度策略: devops/scheduling.md
    - 维护指南:
      - 日常维护: devops/routine.md
      - 备份策略: devops/backup.md
  - 硬件概览: 
    - 配置清单: hardware/hardware.md
    - 拓扑结构: hardware/topology.md
    - 存储设备: hardware/storage-list.md
  - 附录:
    - 常见问题: appendix/faq.md
    - 版本历史: appendix/version-history.md
    - 扩展计划: appendix/roadmap.md

plugins:
  - search

markdown_extensions:
- codehilite

# extra_css:
#   - css/custom.css